/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import io.ktor.server.engine.embeddedServer
import io.ktor.server.netty.Netty
import io.ktor.server.application.Application
import io.ktor.server.application.call
import io.ktor.server.application.install
import io.ktor.server.routing.routing
import io.ktor.server.request.receive
import io.ktor.server.response.respond
import io.ktor.server.response.respondText
import io.ktor.serialization.kotlinx.json.json
import io.ktor.server.plugins.contentnegotiation.ContentNegotiation
import io.ktor.http.ContentType
import kotlinx.serialization.Serializable
import io.ktor.server.routing.post
import io.ktor.server.routing.get
import io.ktor.server.plugins.callloging.CallLogging
import io.ktor.server.plugins.statuspages.StatusPages
import io.ktor.server.plugins.statuspages.exception
import org.example.validator.DefaultPasswordValidator
import org.example.openapi.buildOpenApi

@Serializable
data class PasswordRequest(val password: String)

@Serializable
data class PasswordResponse(val valid: Boolean, val message: String? = null, val details: List<String> = emptyList())

fun Application.module(validator: org.example.validator.PasswordValidator = DefaultPasswordValidator()) {
    install(CallLogging)
    install(StatusPages) {
        exception<Throwable> { call, cause ->
            call.application.environment.log.error("Unhandled error", cause)
            call.respond(mapOf("error" to (cause.message ?: "internal error")))
        }
    }

    install(ContentNegotiation) {
        json()
    }

    routing {
        get("/health") {
            call.respond(mapOf("status" to "UP"))
        }

        post("/validate") {
            val req = call.receive<PasswordRequest>()
            val result = validator.validate(req.password)
            call.respond(PasswordResponse(result.valid, result.message, result.details))
        }

        get("/openapi.json") {
            call.respondText(buildOpenApi(), ContentType.Application.Json)
        }

        get("/docs") {
            val html = """
                <!doctype html>
                <html>
                <head>
                    <meta charset="utf-8" />
                    <title>Swagger UI - Password Validator</title>
                    <link rel="stylesheet" href="https://unpkg.com/swagger-ui-dist@4/swagger-ui.css" />
                </head>
                <body>
                    <div id="swagger-ui"></div>
                    <script src="https://unpkg.com/swagger-ui-dist@4/swagger-ui-bundle.js"></script>
                    <script>
                        const ui = SwaggerUIBundle({
                            url: '/openapi.json',
                            dom_id: '#swagger-ui',
                        })
                    </script>
                </body>
                </html>
            """.trimIndent()
            // Retorna o HTML para o cliente com o tipo de conteúdo correto
            call.respondText(html, ContentType.Text.Html)
        }
    }
}

fun main() {
    val port = System.getenv("PORT")?.toIntOrNull() ?: 8080
    embeddedServer(Netty, port = port, module = Application::module).start(wait = true)
}
