/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import kotlin.test.Test
import kotlin.test.assertTrue

class AppTest {
    @Test
    fun validatorSanity() {
        // a minimal sanity check to ensure validator is accessible
        val v = org.example.validator.DefaultPasswordValidator()
        assertTrue(v.isValid("AbTp9!fok"))
    }
}
